### ISSUE TITLE
option --latex-engine changed to --pdf-engine 

### ISSUE THREAD

**Issue by bsamadi** [CoinCulture/claw#18]
Please change --latex-engine to --pdf-engine in line 220 in contracts.go to be able to generate a PDF using the new version of pandoc. 

Thank you for sharing claw!

**Comment by zramsay** [comment]
@bsamadi thanks for the find. I'm curious how you find claw in its current state? We haven't really been using it since it's missing some feature. Is there anything you'd like to see added / improved?
