### ISSUE TITLE
Go get fails

### ISSUE THREAD

**Issue by xla** [CoinCulture/claw#28]
Resoanbly up-to-date linux:
```
|> uname -a
Linux xla-xps01 5.0.2-arch1-1-ARCH #1 SMP PREEMPT Thu Mar 14 18:47:49 UTC 2019 x86_64 GNU/Linux
```

I run into the following issue when trying to go get:
```
|> go get github.com/CoinCulture/claw
# github.com/CoinCulture/claw
../../../github.com/CoinCulture/claw/util.go:37:9: undefined: blackfriday.Run
../../../github.com/CoinCulture/claw/util.go:37:28: undefined: blackfriday.WithNoExtensions
```

**Comment by zramsay** [comment]
added `dep` for the dockerfile, and updated to v2 because https://github.com/russross/blackfriday#known-issue-with-dep

updated master with https://github.com/CoinCulture/claw/commit/bb8fab0fe425a6f71d855aeb72eaa459a269635b
